language: csharp
dotnet: 2.1.300

sudo: false  # use the new container-based Travis infrastructure
dist: trusty
cache:
  - yarn: true
  

before_script:
  - nvm install 7
  - nvm use 7
  #install yarn globally
  - npm install -g yarn

cache:
  yarn: true

script:
  - ./build.sh